module.exports = {
    app_contents: require("./M_app_contents"),
    app_versions: require("./M_app_versions"),
    chat_rooms: require("./M_chat_rooms"),
    chats: require("./M_chats"),
    communities_albums: require("./M_communities_albums"),
    communities: require("./M_communities"),
    email_verifications: require("./M_email_verifications"),
    faqs: require("./M_faqs"),
    guests: require("./M_guests"),
    notifications: require("./M_notifications"),
    pet_albums: require("./M_pet_albums"),
    pet_likes: require("./M_pet_likes"),
    pets: require("./M_pets"),
    service_albums: require("./M_service_albums"),
    service_likes: require("./M_service_likes"),
    services: require("./M_services"),
    user_albums: require("./M_user_albums"),
    user_reviews: require("./M_user_reviews"),
    user_sessions: require("./M_user_sessions"),
    users: require("./M_users"),
};